module.exports = [ { name: 'api_test.todo.txt',
    path_lower: '/todo/api_test.todo.txt',
    id: 'id:DUCBZSTNHIAAAAAAAAAAAQ',
    client_modified: '2016-01-18T16:09:32Z',
    server_modified: '2016-01-18T16:09:35Z',
    rev: '18eb5475001a3a9b',
    size: 153,
    text: 'always present and uncompleted\nx completed in second revision added in first\nadded in second revision\nx always present and completed\ncompleted in first, uncompleted in second\n' },
  { name: 'api_test.todo.txt',
    path_lower: '/todo/api_test.todo.txt',
    id: 'id:DUCBZSTNHIAAAAAAAAAAAQ',
    client_modified: '2016-01-18T15:54:54Z',
    server_modified: '2016-01-18T15:54:58Z',
    rev: '18eb546f001a3a9b',
    size: 113,
    text: 'always present and uncompleted\ncompleted in second revision added in first\nx always present and completed\ncreated in first, deleted in second\nx completed in first, uncompleted in second\n' } ];
